import Foundation

nonisolated enum LetterGameLogTemplate: String, Equatable, Sendable {
    case openNoProgress1 = "OPEN_NO_PROGRESS_1"
    case openNoProgress2 = "OPEN_NO_PROGRESS_2"
    case openNoProgressStreak1 = "OPEN_NO_PROGRESS_STREAK_1"
    case openNoProgressStreak2 = "OPEN_NO_PROGRESS_STREAK_2"
    case openRepeated1 = "OPEN_REPEATED_1"
    case openRepeated2 = "OPEN_REPEATED_2"
    case openFew1 = "OPEN_FEW_1"
    case openFew2 = "OPEN_FEW_2"
    case openMany1 = "OPEN_MANY_1"
    case openMany2 = "OPEN_MANY_2"
    case openSuccessStreak1 = "OPEN_SUCCESS_STREAK_1"
    case openSuccessStreak2 = "OPEN_SUCCESS_STREAK_2"
    case guessBlind1 = "GUESS_BLIND_1"
    case guessBlind2 = "GUESS_BLIND_2"
    case guessCorrect1 = "GUESS_CORRECT_1"
    case guessCorrect2 = "GUESS_CORRECT_2"
    case guessCorrectStreak1 = "GUESS_CORRECT_STREAK_1"
    case guessCorrectStreak2 = "GUESS_CORRECT_STREAK_2"
    case guessIncorrect1 = "GUESS_INCORRECT_1"
    case guessIncorrect2 = "GUESS_INCORRECT_2"
    case guessIncorrectStreak1 = "GUESS_INCORRECT_STREAK_1"
    case guessIncorrectStreak2 = "GUESS_INCORRECT_STREAK_2"
    case progressRecovered1 = "PROGRESS_RECOVERED_1"
    case progressRecovered2 = "PROGRESS_RECOVERED_2"
    case hintPublic1 = "HINT_PUBLIC_1"
    case hintPublic2 = "HINT_PUBLIC_2"
    case hintPrivate1 = "HINT_PRIVATE_1"
    case hintPrivate2 = "HINT_PRIVATE_2"
    case hintLowScore1 = "HINT_LOW_SCORE_1"
    case hintLowScore2 = "HINT_LOW_SCORE_2"
    case hintNormal1 = "HINT_NORMAL_1"
    case hintNormal2 = "HINT_NORMAL_2"
    case fallback = "FALLBACK"
}
