// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: shared/song_collection.proto
// Protobuf Java Version: 4.33.0

package org.rhythmeta.maimaid.sharing;

public final class SongCollectionOuterClass {
  private SongCollectionOuterClass() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  static {
  }

  // @@protoc_insertion_point(outer_class_scope)
}
